name: php

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/php.yml
      - php/**/Dockerfile

  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
    paths:
      - .github/workflows/php.yml
      - php/**/Dockerfile

env:
  IMAGE_REGISTRY: ghcr.io

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.3', '7.4', '8.0']
        variant: ['fpm', 'apache']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: build-image
        run: |
          imageTag=${{ github.repository_owner }}/php:${{ matrix.php }}-${{ matrix.variant }};
          docker build --pull --no-cache --tag $imageTag .;
          echo ::set-output name=tag::${imageTag};
        working-directory: php/${{ matrix.php }}/${{ matrix.variant }}

      - name: Digest image
        run: echo ${{ steps.build-image.outputs.digest }}

      - name: Test run image
        run: |
          phpVersion=$(docker run --rm ${{ steps.build-image.outputs.tag }} php -v | grep -o '^PHP [0-9]\.[0-9]');
          if [ "$phpVersion" == "PHP ${{ matrix.php }}" ];
          then
            echo $phpVersion;
          else
            exit 1;
          fi

      - name: Push image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.TOKEN_PACKAGE }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${{ steps.build-image.outputs.tag }}
