name: wp

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - 'wp/**/Dockerfile'

jobs:

  wp:
    name: Build PHP Image
    runs-on: ubuntu-latest

    env:
      LATEST_PHP: '8.0'
      LATEST_VARIANT: 'apache'

    strategy:
      fail-fast: true
      matrix:
        php: ['7.3', '7.4', '8.0']
        variant: ['fpm', 'apache']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: build-image
        run: |
          imageTag=${{ github.repository_owner }}/php:${{ matrix.php }}-${{ matrix.variant }};
          docker build --pull --no-cache --tag $imageTag .;
          echo ::set-output name=tag::${imageTag};
        working-directory: wp/php${{ matrix.php }}/${{ matrix.variant }}

      - name: Run image
        run: |
          docker images
          phpVersion=$(docker run --rm ${{ steps.build-image.outputs.tag }} php -v | grep -o '^PHP [0-9]\.[0-9]');
          if [ "$phpVersion" == "PHP ${{ matrix.php }}" ];
          then
            echo $phpVersion;
          else
            exit 1;
          fi
